import { v } from "convex/values";

export const normalizedMatchValidator = v.object({
  source: v.string(),
  sourceMatchId: v.string(),
  homeTeam: v.string(),
  awayTeam: v.string(),
  startTime: v.number(),
  startTimeIso: v.string(),
  sportId: v.number(),
  sportName: v.string(),
  sportSlug: v.string(),
  competitionId: v.string(),
  competitionName: v.string(),
  competitionPriority: v.number(),
  countryCode: v.string(),
  countryName: v.string(),
  result: v.string(),
  status: v.number(),
  statusDesc: v.string(),
  isLive: v.boolean(),
  producerState: v.number(),
  priority: v.number(),
  totalMarkets: v.number(),
  mainMarketId: v.string(),
  mainMarketName: v.string(),
  mainMarketOutcomes: v.string(),
  hasJenga: v.boolean(),
});

export const normalizedMarketValidator = v.object({
  source: v.string(),
  sourceMatchId: v.string(),
  marketKey: v.string(),
  subTypeId: v.number(),
  name: v.string(),
  marketType: v.string(),
  marketTypes: v.array(v.string()),
  oddsCount: v.number(),
  marketPriority: v.number(),
  hasActiveOdds: v.boolean(),
});

export const normalizedOddValidator = v.object({
  source: v.string(),
  sourceOddId: v.string(),
  sourceMatchId: v.string(),
  marketKey: v.string(),
  subTypeId: v.number(),
  outcomeId: v.string(),
  specifiers: v.string(),
  outcomeName: v.string(),
  outcomeAlias: v.string(),
  marketName: v.string(),
  marketType: v.string(),
  marketPriority: v.number(),
  marketNameTemplate: v.string(),
  marketStatus: v.number(),
  status: v.number(),
  oddValue: v.number(),
  prevOddValue: v.number(),
  outcomeDef: v.string(),
  probabilityValue: v.number(),
  priority: v.number(),
  confirmed: v.number(),
  isPlayer: v.number(),
  sourceCreatedAt: v.union(v.string(), v.null()),
  sourceModifiedAt: v.union(v.string(), v.null()),
});
